ACCOUNT_TYPE_CHOICES = (
    ('MAIN', "MAIN"),
    ('DOLLAR ACCOUNT', "DOLLAR ACCOUNT"),
    ('TARGET SAVINGS', "TARGET SAVINGS"),
    ('INVESTMENT ACCOUNT', "INVESTMENT ACCOUNT"),
)

CURRENCY_CHOICES = (
    ("USD", "USD"),
    ("NGN", "NGN"),
)

STATUS_CHOICES = (
    ("ACTIVE", "ACTIVE"),
    ("DORMANT", "DORMANT"),
    ("CLOSED", "CLOSED"),
)