# Generated by Django 5.1.3 on 2024-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('NIN', 'NIN'), ("Voter's Card", "Voter's Card"), ('Passport', 'Passport')], max_length=20),
        ),
    ]
