# Generated by Django 5.1.3 on 2024-11-07 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('MAIN', 'MAIN'), ('DOLLAR ACCOUNT', 'DOLLAR ACCOUNT'), ('TARGET SAVINGS', 'TARGET SAVINGS'), ('INVESTMENT ACCOUNT', 'INVESTMENT ACCOUNT')], max_length=30)),
                ('account_title', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=5)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DORMANT', 'DORMANT'), ('CLOSED', 'CLOSED')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_transaction_date', models.DateTimeField(blank=True)),
                ('withdrawal_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maturity_date', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
