# Generated by Django 5.1.3 on 2024-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='last_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
