# Generated by Django 5.1.3 on 2024-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_last_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='deposit_limit',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
    ]
