# Generated by Django 5.1.3 on 2024-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_balance_alter_accounts_deposit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
